web/router.ex
defmodule Backlash.Router do
  use Backlash.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Backlash.Auth, repo: Backlash.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Backlash do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/users/statistics", UserController, :statistics
    get "/projects/ranking", ProjectController, :ranking
    get "/projects/my_projects", ProjectController, :my_projects
    get "/setups/my_setups", SetupController, :my_setups

    resources "/projects", ProjectController
    resources "/setups", SetupController
    resources "/targets", TargetController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create]
    resources "/admin", AdminController, only: [:index]

    get "/projects/:id/repute", ProjectController, :repute
    get "/projects/:id/unrepute", ProjectController, :unrepute
    get "/projects/:id/setups", ProjectController, :setups

    get "/signout", SessionController, :delete
    get "/signin", SessionController, :new
    get "/signup", UserController, :new

    get "/setups/:id/derelate/:project_id", SetupController, :derelate
  end

  # Other scopes may use custom stacks.
  # scope "/api", Backlash do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Backlash.LayoutView do
  use Backlash.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Backlash - Providers of half decent scripts</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "header.html", conn: @conn, current_user: @current_user %>

    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>

    <main role="main" class="main-body">
      <div class="sidebar">
        <%= render "sidebar_desktop.html", conn: @conn, current_user: @current_user %>
      </div>

      <div class="main-content">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </main>

    <%= render "footer.html" %>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/header.html.eex
<header>
  <!-- <div class="prev-header">
    <center><img class="backlash-logo" src="<%= static_path(@conn, "/images/logo.png") %>"/></center>
  </div>
  -->

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><%= link("PROJECTS", to: project_path(@conn, :index)) %></li>
        <li><%= link("SETUPS", to: setup_path(@conn, :index)) %></li>
        <li><%= link("TARGETS", to: target_path(@conn, :index)) %></li>
        <%= if @current_user do %>
          <li><%= link("EDIT PROFILE", to: user_path(@conn, :edit, @current_user.id)) %></li>
          <li><%= link "SIGNOUT", to: session_path(@conn, :delete) %></li>
          <%= if @current_user.admin do %>
            <li><%= link "ADMIN PANEL", to: admin_path(@conn, :index) %></li>
          <% end %>
        <% else %>
          <li><%= link("SIGNUP", to: user_path(@conn, :new)) %></li>
          <li><%= link("SIGNIN", to: session_path(@conn, :new)) %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

web/templates/layout/sidebar_desktop.html.eex
<div class="sidebar-desktop">
  <div class="section">
    <div class="item section-title">
      <%= link("Projects", to: project_path(@conn, :index)) %>
    </div>
    <%= if @current_user do %>
      <div class="item section-item">
        <%= link("My Projects", to: project_path(@conn, :my_projects)) %>
      </div>
    <% end %>
    <div class="item section-item">
      <%= link("Statistics", to: project_path(@conn, :index)) %>
    </div>
    <div class="item section-item">
      <%= link("Ranking", to: project_path(@conn, :ranking)) %>
    </div>
  </div>

  <div class="section">
    <div class="item section-title">
      <%= link("Setups", to: setup_path(@conn, :index)) %>
    </div>
    <%= if @current_user do %>
      <div class="item section-item">
        <%= link("My Setups", to: setup_path(@conn, :my_setups)) %>
      </div>
      <div class="item section-item">
        <%= link("New Setup", to: setup_path(@conn, :new)) %>
      </div>
    <% end %>
    <div class="item section-item">
      <%= link("Statistics", to: setup_path(@conn, :index)) %>
    </div>
    <div class="item section-item">
      <%= link("Ranking", to: setup_path(@conn, :index)) %>
    </div>
    <div class="item section-item">
      <%= link("Guide", to: setup_path(@conn, :index)) %>
    </div>
  </div>

  <div class="section">
    <div class="item section-title">
      <%= link("Targets", to: target_path(@conn, :index)) %>
    </div>
    <%= if @current_user do %>
      <div class="item section-item">
        <%= link("My Targets", to: project_path(@conn, :index)) %>
      </div>
    <% end %>
    <div class="item section-item">
      <%= link("Statistics", to: project_path(@conn, :index)) %>
    </div>
    <div class="item section-item">
      <%= link("Ranking", to: project_path(@conn, :index)) %>
    </div>
  </div>

  <div class="section">
    <div class="item section-title">
      <%= link("Users", to: user_path(@conn, :index)) %>
    </div>
    <%= if @current_user do %>
      <div class="item section-item">
        <%= link("My Profile", to: user_path(@conn, :show, @current_user.id)) %>
      </div>
      <div class="item section-item">
        <%= link("Edit Info", to: user_path(@conn, :edit, @current_user.id)) %>
      </div>
    <% end %>
    <div class="item section-item">
      <%= link("Statistics", to: user_path(@conn, :statistics)) %>
    </div>
  </div>
</div>